name: publish-docker
on:
  push:
    branches:
      - master
  schedule:
    # Weekly on Sundays at 02:00
    - cron: '0 2 * * 0'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Get ISCE Source Code
      run: |
        wget https://github.com/isce-framework/isce2/archive/v2.3.2.tar.gz
    - name: Build Image and Push to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: scottyhq/github-action
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        cache: ${{ github.event_name != 'schedule' }}
